---
- name: Install and configure Nginx
  hosts: managed_nodes
  become: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
        
    - name: Create custom index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Ansible Managed Server</title></head>
          <body>
            <h1>Hello from Ansible!</h1>
            <p>This server was configured by Ansible automation.</p>
            <p>Hostname: {{ ansible_hostname }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'
        
    - name: Verify Nginx is running
      command: systemctl is-active nginx
      register: nginx_status
      
    - name: Display Nginx status
      debug:
        msg: "Nginx status: {{ nginx_status.stdout }}"
